server:
  port: 8000

spring:
  profiles:
    active: dev
    include: feign
  application:
    name: service-order

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active}

#---
#spring:
#  config:
#    import:
#      - nacos:common.properties?group=order
#      - nacos:database.properties?group=order
#    activate:
#      on-profile: dev

#---
#spring:
#  config:
#    import:
#      - nacos:common.properties?group=order
#     ## - nacos:database.properties?group=order
#    activate:
#      on-profile: prod
